spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:./db/emt
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  main:
    banner-mode: OFF      
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml