spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:h2:./db/emt
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: rania.mensi.2000@gmail.com
    password: tgipeqnnrvdotzbg
    properties:
       mail.smtp.auth: true
       mail.smtp.starttls.enable: true
  main:
    banner-mode: OFF      
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml